import { nanoid } from 'nanoid'
import { FaHtml5, FaJs, FaReact } from 'react-icons/fa'

export const links = [
  { id: nanoid(), href: '#home', text: 'home' },
  { id: nanoid(), href: '#skills', text: 'skills' },
  { id: nanoid(), href: '#about', text: 'about' },
  { id: nanoid(), href: '#projects', text: 'projects' },
]

export const skills = [
  {
    id: nanoid(),
    title: 'HTML&CSS',
    icon: <FaHtml5 className="h-16 w-16 text-emerald-500" />,
    text: 'Highly skilled in HTML & CSS, adeptly crafting visually appealing and responsive websites for optimal user experiences.',
  },
  {
    id: nanoid(),
    title: 'Javascript',
    icon: <FaJs className="h-16 w-16 text-emerald-500" />,
    text: 'Expertise in JavaScript, building interactive and dynamic web applications with a focus on seamless user interactions and functionality',
  },
  {
    id: nanoid(),
    title: 'React',
    icon: <FaReact className="h-16 w-16 text-emerald-500" />,
    text: 'Advanced proficiency in React, developing efficient and interactive front-end applications with a strong emphasis on component-based architecture.',
  },
]

export const projects = [
  {
    id: nanoid(),
    img: '/react-website.png',
    url: 'https://react-website-non.netlify.app/',
    github: 'https://github.com/n0nnnnc/react-website',
    title: 'react website',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/backroads-web-application.png',
    url: 'https://backroads-web-application.netlify.app/',
    github: 'https://github.com/n0nnnnc/backroads-app',
    title: 'backroads web application',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/birthday-buddy.png',
    url: 'https://my-birthday-buddy-site.netlify.app/',
    github: 'https://github.com/n0nnnnc/birthday-buddy-main',
    title: 'birthday buddy',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/tours.png',
    url: 'https://react-my-tours-site.netlify.app/',
    github: 'https://github.com/n0nnnnc/tours',
    title: 'tours',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/reviews.png',
    url: 'https://rect-my-reviews-site.netlify.app/',
    github: 'https://github.com/n0nnnnc/Reviews-main',
    title: 'reviews',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/accordian.png',
    url: 'https://react-accordian-alt.netlify.app/',
    github: 'https://github.com/n0nnnnc/Accordian-project-alt',
    title: 'accordian',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/menu.png',
    url: 'https://react-my-menu-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Menu-projects',
    title: 'menu',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/tabs.png',
    url: 'https://react-my-tab-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Tabs-project',
    title: 'tabs  ',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/slider.png',
    url: 'https://reactmysliderproject.netlify.app/',
    github: 'https://github.com/n0nnnnc/Slider-project',
    title: 'slider',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/lorem-ipsum.png',
    url: 'https://react-my-lorem-ipsum-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Lorem-Ipsum-project',
    title: 'lorem ipsum',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/color-generator.png',
    url: 'https://react-my-color-generator-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Color-generator-project',
    title: 'color generator',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/grocery-bud.png',
    url: 'https://react-my-grocery-bud.netlify.app/',
    github: 'https://github.com/n0nnnnc/Grocery-Bud',
    title: 'grocery bud',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/navbar.png',
    url: 'https://react-my-navbar-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Navbar-project',
    title: 'navbar',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/sidebar_and_modal.png',
    url: 'https://react-my-sidebar-modal-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Sidebar-and-Modal-project',
    title: 'sidebar and modal',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/strapi_menu.png',
    url: 'https://react-my-strapi-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Strapi--project',
    title: 'strapi menu',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/cart.png',
    url: 'https://react-my-cart-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/Cart-project',
    title: 'cart',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/unsplash_images.png',
    url: 'https://react-my-unsplash-images-project.netlify.app/',
    github: 'https://github.com/n0nnnnc/temp-vite-images',
    title: 'unsplash images',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/contentful_cms.png',
    url: 'https://react-temp-contentful-app.netlify.app/',
    github: 'https://github.com/n0nnnnc/temp-contentful-app',
    title: 'contentful CMS',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/mix_master.png',
    url: 'https://my-react-mix-master.netlify.app/',
    github: 'https://github.com/n0nnnnc/mix-master',
    title: 'mix master',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
  {
    id: nanoid(),
    img: '/e-commerce.png',
    url: 'https://my-react-comfy-store-app.netlify.app/',
    github: 'https://github.com/n0nnnnc/comfy-store',
    title: 'e-commerce',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores aperiam porro impedit tenetur quo hic omnis doloribus dolores enim deleniti.',
  },
]
